// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package minewire

import (
	"github.com/wangle201210/studyGo/design/minewire/lib"
	"github.com/wangle201210/studyGo/design/minewire/lib1"
)

// Injectors from wire.go:

// wireApp init kratos application.
func startApp() *App {
	libLib := lib.New()
	lib1Lib1 := lib1.New(libLib)
	app := New(libLib, lib1Lib1)
	return app
}
