// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInfo = "info"

// Info mapped from table <info>
type Info struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Mid         int32     `gorm:"column:mid;not null" json:"mid"`                                         // 用户id
	ArchiveView int64     `gorm:"column:archive_view;not null" json:"archive_view"`                       // 播放数
	Likes       int64     `gorm:"column:likes;not null" json:"likes"`                                     // 获赞数
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName Info's table name
func (*Info) TableName() string {
	return TableNameInfo
}
