server:
  http:
    addr: 0.0.0.0:8088
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9099
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:bilibiliroot@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
