package devlop

import (
	"fmt"
	"testing"
)

func TestSql2proto(t *testing.T) {
	s := "CREATE TABLE `user` (\n  `pk` int(11) unsigned NOT NULL AUTO_INCREMENT,\n  `id` int(11) unsigned NOT NULL,\n  `username` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '''''' COMMENT '用户名',\n  `type` tinyint(4) unsigned NOT NULL DEFAULT '3' COMMENT '用户类型, 1为医生用户, 2为机构用户, 3为手机注册用户，4为游客(仅redis存在)，5为微信用户，6为QQ用户，11为营销平台患者，33第三方账号',\n  `sex` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '性别 0未设置 1男 2女',\n  `avatar` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '''''',\n  `cellphone` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '''''',\n  `password` char(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '''''' COMMENT '用户登录密码',\n  `salt` char(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '''''' COMMENT '密码盐',\n  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '''''',\n  `isOff` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'push 开关',\n  `insertTime` int(10) unsigned NOT NULL DEFAULT '0',\n  `modifyTime` int(10) unsigned NOT NULL DEFAULT '0',\n  `lastActiveTime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最后一次访问时间',\n  `regPlatform` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'u' COMMENT '注册来源a Android,i IOS,w Web,u Unknown',\n  `regChannel` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '渠道来源',\n  `blockFlag` tinyint(4) unsigned NOT NULL DEFAULT '1' COMMENT '屏蔽状态 1-正常 2-屏蔽',\n  `deviceId` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT 'unknow' COMMENT '设备号',\n  `regIp` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT 'unknow' COMMENT '注册ip',\n  `appVersion` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT 'unknow' COMMENT '版本号',\n  `userPlatform` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '账号平台。默认为空。代表社区账号',\n  `userPlatformRole` tinyint(3) unsigned NOT NULL COMMENT '账号角色，由各自业务逻辑决定',\n  `optionUserId` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '操作用户Id',\n  `delTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '注销时间',\n  PRIMARY KEY (`pk`),\n  UNIQUE KEY `idx_id` (`id`),\n  KEY `idx_cellphone` (`cellphone`),\n  KEY `idx_type_ct` (`type`,`insertTime`),\n  KEY `emailIndex` (`email`(128)),\n  KEY `idx_insert_time` (`insertTime`),\n  KEY `idx_username` (`username`),\n  KEY `idx_cp_up` (`cellphone`,`userPlatform`),\n  KEY `idx_upf` (`userPlatform`),\n  KEY `idx_deviceid` (`deviceId`(10)) USING BTREE,\n  KEY `idx_lastActiveTime_userPlatform` (`lastActiveTime`,`userPlatform`)\n) ENGINE=InnoDB AUTO_INCREMENT=32291657 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;"
	s2p2 := Sql2proto(s, WithCommentPos("right"), WithGogo())
	fmt.Println(s2p2.String())
}
